services:
  deno-app:
    build: .
    container_name: deno-app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
