services:
  deno-app:
    image: denoland/deno:2.3.3
    container_name: deno-app
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: run --allow-net --allow-read --allow-write --allow-env src/main.ts
    ports:
      - 5000:5000"
    # environment:
    #   - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
    #   - PORT=${PORT}
    #   - JWT_SECRET=${JWT_SECRET}
    #   - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    #   - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #   - AWS_BUCKET=${AWS_BUCKET}
    #   - AWS_REGION=${AWS_REGION}
    -depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    # environement:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
